config/routes.rb
Rails.application.routes.draw do

  get 'items_imports/new'
  get 'items_imports/create'
  get 'activities/index'
  match '*path', via: [:options], to: lambda {|_| [204, { 'Content-Type' => 'text/plain' }]}
  resources :track do
    member do
      get :get_coordinates
    end
  end
  resources :blogs, except: [:destroy]
  resources :items_imports, only: [:new, :create]
  namespace :admin do
    root 'dashboard#index'
    devise_scope :user do
      get '/sign_in' => "/users/sessions#new" , as: :sign_in
      get '/sign_up' => "/users/registrations#new", as: :sign_up


    end
    # devise_scope :admin do
    #   get '/sign_up' => "/admin/fleet_individual/new", as: :sign_up
    # end
    get "/dashboard/cargo-owners" => "dashboard#cargo_owners" , as: :cargo_owners
    get "/dashboard/fleet-owners" => "dashboard#fleet_owners" , as: :fleet_owners
    get "/shipment_dashboard/posted-shipments" => "shipment_dashboard#shipment_posted" , as: :shipment_posted
    get "/shipment_dashboard/fleet-owners" => "shipment_dashboard#fleet_owners" , as: :shipment_upcoming
    get "/shipment_dashboard/fleet-owners" => "shipment_dashboard#fleet_owners" , as: :shipment_ongoing

    post "/dashboard/mark-verified/:company_id" => "dashboard#mark_verified", as: :mark_verified
    post "/dashboard/mark-featured/:company_id" => "dashboard#mark_featured", as: :mark_featured
    post "/dashboard/mark-blacklisted/:company_id" => "dashboard#mark_blacklisted", as: :mark_blacklisted
    post "/dashboard/tax_invoice/:company_id" => "dashboard#tax_invoice", as: :tax_invoice
    post "/dashboard/mark-safe-for-cash-on-delivery/:company_id" => "dashboard#mark_safe_for_cash_on_delivery", as: :mark_safe_for_cash_on_delivery
    get "/dashboard/add_vehicle" => "dashboard#add_vehicle", as: :add_dashboard_vehicle   
    post "/dashboard/add_fleet_dashboard_vehicle" => "dashboard#add_fleet_dashboard_vehicle", as: :add_fleet_dashboard_vehicle
    get "/dashboard/show-user/:user_id" => "dashboard#show_user", as: :show_user
    get "/dashboard/assigned_shipment/:company_id" => "dashboard#assigned_shipment", as: :assigned_shipment
    get "/dashboard/edit-user/:user_id" => "dashboard#edit_user", as: :edit_user
    patch "/dashboard/update-user/:user_id" => "dashboard#update_user", as: :update_user
    get "/dashboard/cargo-contracts/:company_id" => "dashboard#cargo_contracts", as: :cargo_contracts
    post "/payments/mark-paid-by-cargo/:shipment_id" => "payments#mark_paid_by_cargo", as: :mark_paid_by_cargo
    post "/payments/mark-lorryz-comission-received/:shipment_id" => "payments#mark_lorryz_comission_received", as: :mark_lorryz_comission_received
    post "/payments/mark-paid-to-fleet/:shipment_id" => "payments#mark_paid_to_fleet", as: :mark_paid_to_fleet
    post "/payments/cancel_penalty_amount_received/:shipment_id" => "payments#cancel_penalty_amount_received", as: :cancel_penalty_amount_received
    post "/fleet_individual/add_individual_information" => "fleet_individual#add_individual_information", as: :add_individual_information
    post "/fleet_individual/add_vehicle" => "fleet_individual#add_vehicle", as: :add_vehicle   
    post "/fleet_individual/add_fleet_individual_vehicle" => "fleet_individual#add_fleet_individual_vehicle", as: :add_fleet_individual_vehicle
  
     post "/cargo_individual/add_cargo_individual_information" => "cargo_individual#add_cargo_individual_information", as: :add_cargo_individual_information
     post "/cargo_individual/add_cargo_company_information" => "cargo_company#add_cargo_company_information", as: :add_cargo_company_information

     post "/shipments/add_admin_shipment_details" => "shipments#add_admin_shipment_details", as: :add_admin_shipment_details
  
     get "/dashboard/edit-history/:user_id" => "dashboard#edit_history", as: :edit_history

     resources :companies, :only => [  ] do
      collection do
        post :add_company_information
        post :add_individual_information
        patch :add_individual_information
        get :edit
        get :get_individual_information
        put :presign_upload
      end
    end
    resources :primary_vehicle
    resources :company_information do
    get :autocomplete_company_information_name, :on => :collection

  end
    resources :pages
    resources :gps_vehicle , except: [:destroy]
    resources :soa    do
      collection do
        get :country_accounts
        get :customer_accounts

        end
      end

    resources :fleet_individual , except: [:destroy] do  collection do
      put :presign_upload
    end end
    resources :cargo_individual , except: [:destroy]
    resources :cargo_company , except: [:destroy]
    resources :invoices , only: [:show]
    resources :countries , except: [:destroy]
    resources :preferred_location , except: [:destroy]
    resources :enquiries , except: [:destroy]

    resources :vehicle_types, except: [:destroy]

    resources :blogs, except: [:destroy]
    resources :instant_rates, except: [:destroy]
    resources :automated_email_configuration, except: [:destroy]

    resources :locations
    resources :tcn , only: [:show]
    resources :financial_report , only: [:index]

    resources :fleet_invoices , only: [:show]

    resources :change_destination_requests
    resources :vendor, except: [:destroy]
    resources :admin_notification, except: [:destroy]

    resources :shipments do
      collection do

      get :cargo_invoice
      put :presign_upload

      end

      member do
        delete :cancel
        get :assign_vehicle
        get :send_completed_email

        
        get :assign_cost
        get :email
        get :edit_history
        get :get_coordinates
        patch :status_email
      end
      collection do
        post :get_bulk_coordinates

      end
    end
    get '/reports', to: 'reports#index'
    get '/onlinedrivers', to: 'onlinedrivers#index'
    resources :users  do

            get :autocomplete_user_fleet_owner_name, :on => :collection
            get :autocomplete_user_cargo_owner_name, :on => :collection
            get :autocomplete_vehicle_vehicle_name, :on => :collection


      collection do
        post :get_all_drivers
        post :get_all_drivers_filtered
        get :change_password


      end
    end


    resources :payments
  end

  namespace :moderator do
    root 'dashboard#index'
    get "/dashboard/cargo-owners" => "dashboard#cargo_owners" , as: :cargo_owners
    get "/dashboard/show-user/:user_id" => "dashboard#show_user", as: :show_user
    get "/dashboard/edit-user/:user_id" => "dashboard#edit_user", as: :edit_user
    patch "/dashboard/update-user/:user_id" => "dashboard#update_user", as: :update_user
    get "/dashboard/cargo-contracts/:company_id" => "dashboard#cargo_contracts", as: :cargo_contracts
    post "/dashboard/mark-verified/:company_id" => "dashboard#mark_verified", as: :mark_verified
    post "/dashboard/mark-featured/:company_id" => "dashboard#mark_featured", as: :mark_featured
    get "/dashboard/add_vehicle" => "dashboard#add_vehicle", as: :add_dashboard_vehicle   
    post "/dashboard/add_fleet_dashboard_vehicle" => "dashboard#add_fleet_dashboard_vehicle", as: :add_fleet_dashboard_vehicle
    get "/shipment_dashboard/posted-shipments" => "shipment_dashboard#shipment_posted" , as: :shipment_posted
    get "/shipment_dashboard/fleet-owners" => "shipment_dashboard#fleet_owners" , as: :shipment_upcoming
    get "/shipment_dashboard/fleet-owners" => "shipment_dashboard#fleet_owners" , as: :shipment_ongoing
    post "/dashboard/mark-blacklisted/:company_id" => "dashboard#mark_blacklisted", as: :mark_blacklisted
    post "/dashboard/mark-safe-for-cash-on-delivery/:company_id" => "dashboard#mark_safe_for_cash_on_delivery", as: :mark_safe_for_cash_on_delivery
    get "/dashboard/fleet-owners" => "dashboard#fleet_owners" , as: :fleet_owners
    post "/dashboard/tax_invoice/:company_id" => "dashboard#tax_invoice", as: :tax_invoice
    post "/payments/mark-paid-by-cargo/:shipment_id" => "payments#mark_paid_by_cargo", as: :mark_paid_by_cargo
    post "/payments/mark-lorryz-comission-received/:shipment_id" => "payments#mark_lorryz_comission_received", as: :mark_lorryz_comission_received
    post "/payments/mark-paid-to-fleet/:shipment_id" => "payments#mark_paid_to_fleet", as: :mark_paid_to_fleet
    post "/payments/cancel_penalty_amount_received/:shipment_id" => "payments#cancel_penalty_amount_received", as: :cancel_penalty_amount_received
    post "/fleet_individual/add_individual_information" => "fleet_individual#add_individual_information", as: :add_individual_information
    post "/fleet_individual/add_vehicle" => "fleet_individual#add_vehicle", as: :add_vehicle   
    post "/fleet_individual/add_fleet_individual_vehicle" => "fleet_individual#add_fleet_individual_vehicle", as: :add_fleet_individual_vehicle
    post "/cargo_individual/add_cargo_individual_information" => "cargo_individual#add_cargo_individual_information", as: :add_cargo_individual_information
    post "/cargo_individual/add_cargo_company_information" => "cargo_company#add_cargo_company_information", as: :add_cargo_company_information
    get "/dashboard/assigned_shipment/:company_id" => "dashboard#assigned_shipment", as: :assigned_shipment
    get "/dashboard/edit-history/:user_id" => "dashboard#edit_history", as: :edit_history

    resources :companies, :only => [  ] do
      collection do
        post :add_company_information
        post :add_individual_information
        patch :add_individual_information
        get :edit
        get :get_individual_information
        put :presign_upload
      end
    end
    resources :vendor, except: [:destroy]
      resources :fleet_individual , except: [:destroy] do  collection do
      put :presign_upload
      end end
    resources :cargo_individual , except: [:destroy]
    resources :cargo_company , except: [:destroy]
    resources :invoices , only: [:show]
    resources :tcn , only: [:show]
    resources :fleet_invoices , only: [:show]

app/controllers/api/v1/cargo/shipments_controller.rb
class Api::V1::Cargo::ShipmentsController < Api::V1::ApiController

  before_action :verify_jwt_token
  before_action :set_shipment, only: [:show, :edit, :update, :destroy,:update_documents]

  # GET /shipments
  # GET /shipments.json
  def index
    @shipments = Shipment.all
    render json: @shipments, status: :ok
  end

  # GET /shipments/1
  # GET /shipments/1.json
  def show
  end

  # GET /shipments/new
  def new
    @shipment = Shipment.new
  end

  # GET /shipments/1/edit
  def edit
  end

  # POST /shipments
  # POST /shipments.json
  def create
    @shipment = Shipment.create shipment_params
    puts @shipment.errors.full_messages
    ShipmentMailer.new_shipment( @shipment.id ).deliver_now if  @shipment.errors.blank?

    @shipment.errors.blank? ? ( render "create" , status: :ok ) : (render json: { errors: @shipment.errors.full_messages }, status: :bad_request)
  end

  # PATCH/PUT /shipments/1
  # PATCH/PUT /shipments/1.json
  def update
    if @shipment.update(shipment_params)
			@shipment.bids.destroy_all
			@shipment.update_attributes(is_expired: "false")
      if @shipment.state == "posted"
        @shipment.shipment_posted_notifications
        @shipment.shipment_posted_notifications_moderator


      end

      if @shipment.state == "cancel"
        @shipment.update_attributes(status: "cancel")
      end
      render json: {update: true, status: :ok}
    else
      puts @shipment.errors.full_messages
      render json: { errors:  @shipment.errors.full_messages }, status: :bad_request
    end
  end

  # DELETE /shipments/1
  # DELETE /shipments/1.json
  def destroy
    @shipment.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def calculate_fare
    @shipment = Shipment.new shipment_params
    fare = @shipment.prorate_formula
    distance = @shipment.distance_between_start_and_end_point
    render json: {fare: fare, distance: distance}, status: :ok
  end

  def update_documents
     @shipment.update_attributes(documents: params[:documents])
  end



  def posted
    @shipments = Shipment.where(company_id: params[:company_id]).posted.page params[:page]
  end

  def ongoing
    @shipments = Shipment.where(company_id: params[:company_id]).ongoing.page params[:page]
  end

  def upcoming
    @shipments = Shipment.where(company_id: params[:company_id].to_i, state: ["accepted", "vehicle_assigned"]).page params[:page]
  end


  def completed
    @shipments = Shipment.where(company_id: params[:company_id].to_i).where('state =? OR (state=? AND cancel_by=?)', "completed",'cancel','cargo_owner').page params[:page]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipment
      @shipment = Shipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipment_params
      params.require(:shipment).permit(:pickup_building_name,:cargo_description_url, :drop_building_name, :amount_per_vehicle, :cancel_reason, :cancel_by, :state_event,:payment_option, :state, :id,:company_id, :country_id, :pickup_location, :pickup_date, :pickup_time, :loading_time, :drop_location, :unloading_time, :expected_drop_off, :vehicle_type_id, :no_of_vehicles, :cargo_description, :cargo_packing_type, :pickup_lat, :pickup_lng, :drop_lat, :drop_lng, :drop_city, :pickup_city, :location_id, :amount, :is_pickup_now,{documents: []})
    end
end

app/controllers/moderator/admin_notification_controller.rb
class Moderator::AdminNotificationController <ModeratorController
  before_action :authenticate_user!
  before_action :check_if_moderator
  before_action :set_notification , only: [:edit, :update,:destroy]
  before_action :set_notification_link , only: [:edit, :update , :new , :index ]
  layout 'moderator'
  def index
    @notifcation = AdminNotification.all
    respond_to do |format|
      format.html
    
    end
  end
  def new
    @notification = AdminNotification.new
  end
  def edit
  end
  def create
    @notification = AdminNotification.new(notification_params)
    if @notification.save
      receivers = User.where(:country => current_user.country.try(:id))
      receivers = receivers.where(:role => @notification.receivers )  if !@notification.receivers.all?    
        receivers.each do |receiver|
        # dispathcer = SendSMS.new
        # message = dispathcer.message(user.mobile,"Reminder! Don't forget to pick shipment # #{ self.id } on #{self.pickup_time}")
        Notification.create(
            notifiable_id: @notification.id,
            notifiable_type: "AdminNotification",
            body: @notification.text,
            user_mentioned_id: receiver.id)
        PushNotification.send_notification(
          receiver.os,
            receiver.device_id,
            "",
            @notification.id,
            @notification.text,
            nil,
            ) if receiver.device_id
      end









      
      redirect_to moderator_admin_notification_index_path , notice: "Notification Created Successfully!"
    else
      format.html { render :new }
    end
  end
 
  private
  def set_notification_type
    @notification = AdminNotification.find(params[:id])
  end
  def notification_params
    params.require(:admin_notification).permit(:text,:receivers)
  end
  def set_notification_link
    @notification_link = "active"
  end



end

app/controllers/moderator/automated_email_configuration_controller.rb
class Moderator::AutomatedEmailConfigurationController < ModeratorController
    before_action :authenticate_user!
    before_action :check_if_moderator
    before_action :set_automated_email , only: [ :new,:destroy]
    before_action :set_automated_edit_email , only: [ :edit,:update]

    layout 'moderator'
    def index
      @company_id = params[:company_id]
      @automated_email = AutomatedEmailConfiguration.where(company_id:@company_id)
     

    end
    def new
      @automated_email = AutomatedEmailConfiguration.new
    end
    def edit
    end
    def create
      @automated_email = AutomatedEmailConfiguration.new(automated_email_params)
      print automated_email_params
      if @automated_email.save
        redirect_to moderator_automated_email_configuration_index_path(company_id: params[:automated_email_configuration][:company_id]) , notice: "Instant Rate Created Successfully!"
      else
        format.html { render :new }
      end
    end
    def update
      if @automated_email.update(automated_email_params)
         redirect_to moderator_automated_email_configuration_index_path(company_id: @automated_email.company_id) , notice: " updated successfully!"
        # redirect_to admin_automated_email_configuration_index_path(params[:automated_email_configuration][:company_id]) , notice: "instant_rates Updated Successfully!"
      else
        format.html { render :edit}
      end
    end
    def destroy
      if @automated_email.destroy
        redirect_to admin_instant_rates_path, notice: "instant_rates destroyed successfully"
      else
        redirect_back(fallback_location: admin_instant_rates_path)
      end
    end
    private
    def set_automated_email
        @automated_email = AutomatedEmailConfiguration.where(company_id:params[:company_id])
        @company =params[:company_id]
      end

      def set_automated_edit_email
        @automated_email = AutomatedEmailConfiguration.find(params[:id])
        @company =@automated_email.company_id
      end
    def automated_email_params
      params.require(:automated_email_configuration).permit(:pickup_city, :pickup_country,:drop_country, :drop_city,:dropoff_location,:pickup_location, :email, :company_id)
    end
  
  end
  

app/controllers/moderator/company_information_controller.rb
class Moderator::CompanyInformationController < ModeratorController
    autocomplete :company_information, :name, :extra_data => [:company_id]

end

app/views/moderator/shipments/_assign_vehicle.html.erb
<% redirection_path = params[:query].permit! if params[:query].present? %>
<% redirection_path = params[:query] if params[:query].blank? %>

<%= form_for @shipment, url: moderator_shipment_path(@shipment, query:redirection_path,:protocol => 'https') do |f|%>

    <div class="modal-dialog assing-vehicles-modal">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-body">
    <div class="assing-vehicles-modal-inner" id="<%#@shipment.id%>">
      <div class="close-modal" data-dismiss="modal">
        <%= image_tag 'close-modal.png' %>
      </div>

      <h1>
    <%=  @shipment.shipment_fleets.present? ? "Change" : "Assign" %>
        Driver</h1>
      <%= hidden_field_tag "no_of_vehicles" , @shipment.no_of_vehicles %>
      <div class="shipment-number">
        Shipment No. <%= @shipment.id%>
      </div>
      <div class="address-outer">
        <!-- <div class="distance-holder">
            75 KM
          </div> -->
        <div class="address-one">
          <%=@shipment.pickup_full_address%>
        </div>
        <div class="address-two">
          <%=@shipment.drop_full_address %>
        </div>
      </div>
      <div class="pickup-date-row clearfix">
        <div class="left-col">
          <span>Pick up Date</span>
          <div class="time">
            <span><%= local_time_format @shipment.pickup_time %></span>
            <span class="date"><%=@shipment.pickup_date.strftime(display_date_format) %></span>
          </div>
        </div>
        <div class="right-col">
          <span>Loading time</span>
          <span class="hours"><%=@shipment.loading_time%> Hours</span>
        </div>
      </div>
      <div class="pickup-date-row clearfix">
<!--        <div class="left-col">-->
<!--          <span>Dropoff Date</span>-->
<!--          <div class="time">-->
<!--            <span class="date without-time hours"><%#=@shipment.expected_drop_off.strftime(display_date_format) rescue ""%></span>-->
<!--          </div>-->
<!--        </div>-->
        <div class="right-col">
          <span>Unloading time</span>
          <span class="hours"><%=@shipment.unloading_time%> Hours</span>
        </div>
      </div>
      <div class="payment-mode">
        <span>Payment Mode</span>
        <h6><%=@shipment.try(:payment_option).try(:camelcase)  %></h6>
      </div>
     
      <div class="truck-row">
        <%=@shipment.no_of_vehicles%> x <%=@shipment.vehicle_type.name%>
      </div>
        <div class="choose-vehicle">
          <div>
         <%
         case @shipment.state 
         when "vehicle_assigned","accepted","ongoing"  
         @vehicles_with_drivers  = User.individual_fleet_owners.where(:country_id => @shipment.try(:vehicle_type).country.try(:id))  - User.individual_fleet_owners.busy_fleet_owners - User.individual_fleet_owners.busy_fleet_individual_owners + User.shipment_fleet_individual_owners(@shipment.id) 
         when "initial","posted"
         @vehicles_with_drivers  = User.individual_fleet_owners.where(:country_id => @shipment.try(:vehicle_type).country.try(:id))  - User.individual_fleet_owners.busy_fleet_owners - User.individual_fleet_owners.busy_fleet_individual_owners 
        #  -  User.expired_fleet_users(Date.today()).individual_fleet_owners
             when "completed","cancel" 
         @vehicles_with_drivers  = User.individual_fleet_owners.where(:country_id => @shipment.try(:vehicle_type).country.try(:id)) 

    end %>
          <div class="form-group">
                <%= f.label "*" , class: "label_required"%>
               <%= f.label "", "Specify fleet category ?" %><br> &nbsp; &nbsp; 
                <%= f.label "*", "  All", :value => "true"  %>
             <input type="radio" id="all" name="Category" value="all"checked="checked"> &nbsp; &nbsp; 
                <%= f.label "*", "  Nearest", :value => "false" %>
                 <input type="radio" id="nearest" name="Category" value="nearest">
              </div>


               <%= f.label :vendor, "Specify Vendor if exist?" %>
               <%= f.collection_select :vendor , @vendors , :id , :formatted_cargo_name,{:selected => @shipment.vendor}, {class: "js-example-basic-multiple",  :multiple => true, size: 1}%>
                         <div id ='All'>

            <%= f.label :company_ids , "Choose Individual Fleets" %><br>
            <%= f.collection_select :company_ids , @vehicles_with_drivers , :company_id , :formatted_name,{:selected => @shipment.shipment_fleets.map(&:company_id)}, {class: "js-example-basic-multiple",  :multiple => true, size: 3}%>
          </div>
                 </div>


                <div id ='Nearest' style="visibility:hidden">
       
     
             <%= f.label :company_idss , "Choose Nearest Individual Fleets" %><br>
               <%= f.collection_select :company_idss , @fleets , :company_id , :specific_description,{:selected => @shipment.vendor}, {class: "js-example-basic-multiple",  :multiple => true, size: 1}%>
            
      </div>
               
                   
           
        </div>

        <div class="buttons-holder clearfix">
          <%= f.submit "Save" , class: "submit-btn"%>
        </div>
    </div>
        </div>

      </div>
    </div>
<%end%>
<script>
  setTimeout(function () {
       $('#assign_vehicle_modal form').submit(function () {
          var no_of_vehicles = $("form #no_of_vehicles").val();

          var options = $('form #shipment_company_ids > option:selected');
                    var optionss = $('form #shipment_company_idss > option:selected');

          if (options.length != no_of_vehicles && optionss.length != no_of_vehicles ) {
              msg = "Please select " + no_of_vehicles + " vehicles."
              alert(msg);
              return false;
          }
          var options = $('form #shipment_vendor > option:selected');
          if (options.length > 1 ) {
              msg = "Please select only 1 Vendor" 
              alert(msg);
              return false;
          }
      });
      $('.js-example-basic-multiple').select2({
          closeOnSelect: false,
          width: '90%',
          theme: "classic"
      });
  })


   $('input[type=radio][name=Category]').change(function() {

    if (this.value == 'all') {
          document.getElementById("shipment_company_idss").value = null
      document.getElementById("Nearest").style.visibility="hidden";

     document.getElementById("All").style.visibility="visible";

    }

    else if (this.value == 'nearest') {     
          document.getElementById("shipment_company_ids").value = null

     document.getElementById("Nearest").style.visibility="visible";

     document.getElementById("All").style.visibility="hidden";



     }

});




</script>

app/views/moderator/shipments/_edit.html.erb
<div class="modal fade" id="discount_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Discount Value</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for(@shipment, url: moderator_shipment_path(@shipment)) do |f| %>
        <div class="modal-body">
          <div class="container">
            <div class="form-group">
              <%= f.number_field :discount,class: "form-control",placeholder: "Discount Value",:required => true%>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
      <% end %>  
    </div>
  </div>
</div>

app/views/moderator/shipments/_email.html.erb
<div class="modal fade" id="discount_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Shipment Status</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for(@shipment, url: status_email_moderator_shipment_path(@shipment,:protocol => 'https')) do |f| %>
        <div class="modal-body">
          <div class="container">
         

            <div class="form-group" >
                <%= f.label "*" , class: "label_required"%>
                <%= f.label :to ,"To"%>
                <%=f.text_field :to , placeholder: "To*",value: @shipment.company.cargo_owner.email, class: "form-control"%>
              </div>


              <div class="form-group" >
                <%= f.label "*" , class: "label_required"%>
                <%= f.label :cc ,"CC"%>
                <%=f.text_field :cc , placeholder: "CC*",value: "contact@lorryz.com", class: "form-control"%>
              </div>


              <div class="form-group" >
                <%= f.label "*" , class: "label_required"%>
                <%= f.label :subject ,"Subject"%>
                <%=f.text_field :subject , placeholder: "Subject*",value:" Lorryz - Shipment No : " + @shipment.id.to_s + " Status updated to :" + params[:status], class: "form-control"%>
              </div>

                  <div class="form-group" >
                <%= f.label :message ,"Message"%>
                <%=f.text_field :message , placeholder: "Message",value:"Message", class: "form-control"%>
              </div>
             <%=f.hidden_field :previous_status , value: @shipment.status %>

                <%=f.hidden_field :current_status , value:params[:status] %>

                <%=f.hidden_field :id , value:@shipment.id %>



          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Send Email</button>
        </div>
      <% end %>  
    </div>
  </div>
</div>

app/views/moderator/shipments/_form.html.erb
  <%# form_with(model: shipment, local: true) do |form| %>
<%=form_for @shipment, url: moderator_shipments_path(:protocol => 'https') do |f|%>
  <!--<% if cargo_shipment.errors.any? %>-->
    <!--<div id="error_explanation">-->
      <!--<h2><%= pluralize(cargo_shipment.errors.count, "error") %> prohibited this cargo_shipment from being saved:</h2>-->
<!---->
      <!--<ul>-->
      <!--<% cargo_shipment.errors.full_messages.each do |message| %>-->
        <!--<li><%= message %></li>-->
      <!--<% end %>-->
      <!--</ul>-->
    <!--</div>-->
  <!--<% end %>-->
    <%= render partial: "form_fields" , locals: {f: f, action: action, submit_button_text: "Post Request"}%>
<% end %>

app/views/moderator/shipments/assign_cost.js.erb
$("#assign_cost_modal").html("<%= escape_javascript(render 'assign_cost') %>");
$("#assign_cost_modal").modal('show')

app/views/moderator/shipments/assign_vehicle.js.erb
$("#assign_vehicle_modal").html("<%= escape_javascript(render 'assign_vehicle') %>");
$("#assign_vehicle_modal").modal('show')

app/views/moderator/shipments/email.js.erb
var modalName = "#discount_modal";
$(modalName).remove();
$("body").append("<%= j render "email" %>");
$(modalName).modal("show");
$(modalName).on('hidden.bs.modal', function (e) {
  $(modalName).remove();
});

app/views/moderator/shipments/new.html.erb
<!--<h1>New Cargo Shipment</h1>-->

<%# render 'form', cargo_shipment: @cargo_shipment %>

<%# link_to 'Back', cargo_shipments_path %>

<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <!--<div class="container-fluid">-->
      <!--<div class="row mb-2">-->
        <!--<div class="col-sm-6">-->
          <!--<h1>Shipments</h1>-->
        <!--</div>-->
      <!--</div>-->
    <!--</div>&lt;!&ndash; /.container-fluid &ndash;&gt;-->
  </section>
  <%= render "moderator/shipments/form" , cargo_shipment: @shipment, action: "New"%>
</div>