config/routes.rb
Rails.application.routes.draw do

  get 'items_imports/new'
  get 'items_imports/create'
  get 'activities/index'
  match '*path', via: [:options], to: lambda {|_| [204, { 'Content-Type' => 'text/plain' }]}
  resources :track do
    member do
      get :get_coordinates
    end
  end
  resources :blogs, except: [:destroy]
  resources :items_imports, only: [:new, :create]
  namespace :admin do
    root 'dashboard#index'
    devise_scope :user do
      get '/sign_in' => "/users/sessions#new" , as: :sign_in
      get '/sign_up' => "/users/registrations#new", as: :sign_up


    end
    # devise_scope :admin do
    #   get '/sign_up' => "/admin/fleet_individual/new", as: :sign_up
    # end
    get "/dashboard/cargo-owners" => "dashboard#cargo_owners" , as: :cargo_owners
    get "/dashboard/fleet-owners" => "dashboard#fleet_owners" , as: :fleet_owners
    get "/shipment_dashboard/posted-shipments" => "shipment_dashboard#shipment_posted" , as: :shipment_posted
    get "/shipment_dashboard/fleet-owners" => "shipment_dashboard#fleet_owners" , as: :shipment_upcoming
    get "/shipment_dashboard/fleet-owners" => "shipment_dashboard#fleet_owners" , as: :shipment_ongoing

    post "/dashboard/mark-verified/:company_id" => "dashboard#mark_verified", as: :mark_verified
    post "/dashboard/mark-featured/:company_id" => "dashboard#mark_featured", as: :mark_featured
    post "/dashboard/mark-blacklisted/:company_id" => "dashboard#mark_blacklisted", as: :mark_blacklisted
    post "/dashboard/tax_invoice/:company_id" => "dashboard#tax_invoice", as: :tax_invoice
    post "/dashboard/mark-safe-for-cash-on-delivery/:company_id" => "dashboard#mark_safe_for_cash_on_delivery", as: :mark_safe_for_cash_on_delivery
    get "/dashboard/add_vehicle" => "dashboard#add_vehicle", as: :add_dashboard_vehicle   
    post "/dashboard/add_fleet_dashboard_vehicle" => "dashboard#add_fleet_dashboard_vehicle", as: :add_fleet_dashboard_vehicle
    get "/dashboard/show-user/:user_id" => "dashboard#show_user", as: :show_user
    get "/dashboard/assigned_shipment/:company_id" => "dashboard#assigned_shipment", as: :assigned_shipment
    get "/dashboard/edit-user/:user_id" => "dashboard#edit_user", as: :edit_user
    patch "/dashboard/update-user/:user_id" => "dashboard#update_user", as: :update_user
    get "/dashboard/cargo-contracts/:company_id" => "dashboard#cargo_contracts", as: :cargo_contracts
    post "/payments/mark-paid-by-cargo/:shipment_id" => "payments#mark_paid_by_cargo", as: :mark_paid_by_cargo
    post "/payments/mark-lorryz-comission-received/:shipment_id" => "payments#mark_lorryz_comission_received", as: :mark_lorryz_comission_received
    post "/payments/mark-paid-to-fleet/:shipment_id" => "payments#mark_paid_to_fleet", as: :mark_paid_to_fleet
    post "/payments/cancel_penalty_amount_received/:shipment_id" => "payments#cancel_penalty_amount_received", as: :cancel_penalty_amount_received
    post "/fleet_individual/add_individual_information" => "fleet_individual#add_individual_information", as: :add_individual_information
    post "/fleet_individual/add_vehicle" => "fleet_individual#add_vehicle", as: :add_vehicle   
    post "/fleet_individual/add_fleet_individual_vehicle" => "fleet_individual#add_fleet_individual_vehicle", as: :add_fleet_individual_vehicle
  
     post "/cargo_individual/add_cargo_individual_information" => "cargo_individual#add_cargo_individual_information", as: :add_cargo_individual_information
     post "/cargo_individual/add_cargo_company_information" => "cargo_company#add_cargo_company_information", as: :add_cargo_company_information

     post "/shipments/add_admin_shipment_details" => "shipments#add_admin_shipment_details", as: :add_admin_shipment_details
  
     get "/dashboard/edit-history/:user_id" => "dashboard#edit_history", as: :edit_history

     resources :companies, :only => [  ] do
      collection do
        post :add_company_information
        post :add_individual_information
        patch :add_individual_information
        get :edit
        get :get_individual_information
        put :presign_upload
      end
    end
    resources :primary_vehicle
    resources :company_information do
    get :autocomplete_company_information_name, :on => :collection

  end
    resources :pages
    resources :gps_vehicle , except: [:destroy]
    resources :soa    do
      collection do
        get :country_accounts
        get :customer_accounts

        end
      end

    resources :fleet_individual , except: [:destroy] do  collection do
      put :presign_upload
    end end
    resources :cargo_individual , except: [:destroy]
    resources :cargo_company , except: [:destroy]
    resources :invoices , only: [:show]
    resources :countries , except: [:destroy]
    resources :preferred_location , except: [:destroy]
    resources :enquiries , except: [:destroy]

    resources :vehicle_types, except: [:destroy]

    resources :blogs, except: [:destroy]
    resources :instant_rates, except: [:destroy]
    resources :automated_email_configuration, except: [:destroy]

    resources :locations
    resources :tcn , only: [:show]
    resources :financial_report , only: [:index]

    resources :fleet_invoices , only: [:show]

    resources :change_destination_requests
    resources :vendor, except: [:destroy]
    resources :admin_notification, except: [:destroy]

    resources :shipments do
      collection do

      get :cargo_invoice
      put :presign_upload

      end

      member do
        delete :cancel
        get :assign_vehicle
        get :send_completed_email

        
        get :assign_cost
        get :email
        get :edit_history
        get :get_coordinates
        patch :status_email
      end
      collection do
        post :get_bulk_coordinates

      end
    end
    get '/reports', to: 'reports#index'
    get '/onlinedrivers', to: 'onlinedrivers#index'
    resources :users  do

            get :autocomplete_user_fleet_owner_name, :on => :collection
            get :autocomplete_user_cargo_owner_name, :on => :collection
            get :autocomplete_vehicle_vehicle_name, :on => :collection


      collection do
        post :get_all_drivers
        post :get_all_drivers_filtered
        get :change_password


      end
    end


    resources :payments
  end

  namespace :moderator do
    root 'dashboard#index'
    get "/dashboard/cargo-owners" => "dashboard#cargo_owners" , as: :cargo_owners
    get "/dashboard/show-user/:user_id" => "dashboard#show_user", as: :show_user
    get "/dashboard/edit-user/:user_id" => "dashboard#edit_user", as: :edit_user
    patch "/dashboard/update-user/:user_id" => "dashboard#update_user", as: :update_user
    get "/dashboard/cargo-contracts/:company_id" => "dashboard#cargo_contracts", as: :cargo_contracts
    post "/dashboard/mark-verified/:company_id" => "dashboard#mark_verified", as: :mark_verified
    post "/dashboard/mark-featured/:company_id" => "dashboard#mark_featured", as: :mark_featured
    get "/dashboard/add_vehicle" => "dashboard#add_vehicle", as: :add_dashboard_vehicle   
    post "/dashboard/add_fleet_dashboard_vehicle" => "dashboard#add_fleet_dashboard_vehicle", as: :add_fleet_dashboard_vehicle
    get "/shipment_dashboard/posted-shipments" => "shipment_dashboard#shipment_posted" , as: :shipment_posted
    get "/shipment_dashboard/fleet-owners" => "shipment_dashboard#fleet_owners" , as: :shipment_upcoming
    get "/shipment_dashboard/fleet-owners" => "shipment_dashboard#fleet_owners" , as: :shipment_ongoing
    post "/dashboard/mark-blacklisted/:company_id" => "dashboard#mark_blacklisted", as: :mark_blacklisted
    post "/dashboard/mark-safe-for-cash-on-delivery/:company_id" => "dashboard#mark_safe_for_cash_on_delivery", as: :mark_safe_for_cash_on_delivery
    get "/dashboard/fleet-owners" => "dashboard#fleet_owners" , as: :fleet_owners
    post "/dashboard/tax_invoice/:company_id" => "dashboard#tax_invoice", as: :tax_invoice
    post "/payments/mark-paid-by-cargo/:shipment_id" => "payments#mark_paid_by_cargo", as: :mark_paid_by_cargo
    post "/payments/mark-lorryz-comission-received/:shipment_id" => "payments#mark_lorryz_comission_received", as: :mark_lorryz_comission_received
    post "/payments/mark-paid-to-fleet/:shipment_id" => "payments#mark_paid_to_fleet", as: :mark_paid_to_fleet
    post "/payments/cancel_penalty_amount_received/:shipment_id" => "payments#cancel_penalty_amount_received", as: :cancel_penalty_amount_received
    post "/fleet_individual/add_individual_information" => "fleet_individual#add_individual_information", as: :add_individual_information
    post "/fleet_individual/add_vehicle" => "fleet_individual#add_vehicle", as: :add_vehicle   
    post "/fleet_individual/add_fleet_individual_vehicle" => "fleet_individual#add_fleet_individual_vehicle", as: :add_fleet_individual_vehicle
    post "/cargo_individual/add_cargo_individual_information" => "cargo_individual#add_cargo_individual_information", as: :add_cargo_individual_information
    post "/cargo_individual/add_cargo_company_information" => "cargo_company#add_cargo_company_information", as: :add_cargo_company_information
    get "/dashboard/assigned_shipment/:company_id" => "dashboard#assigned_shipment", as: :assigned_shipment
    get "/dashboard/edit-history/:user_id" => "dashboard#edit_history", as: :edit_history

    resources :companies, :only => [  ] do
      collection do
        post :add_company_information
        post :add_individual_information
        patch :add_individual_information
        get :edit
        get :get_individual_information
        put :presign_upload
      end
    end
    resources :vendor, except: [:destroy]
      resources :fleet_individual , except: [:destroy] do  collection do
      put :presign_upload
      end end
    resources :cargo_individual , except: [:destroy]
    resources :cargo_company , except: [:destroy]
    resources :invoices , only: [:show]
    resources :tcn , only: [:show]
    resources :fleet_invoices , only: [:show]

app/controllers/admin/cargo_individual_controller.rb
class Admin::CargoIndividualController < AdminController
  layout 'admin'

  include UserConcern
  before_action :set_user , only: [:show]
  before_action :set_users_link  , only: [:index , :show]
  before_action :check_if_super_admin , only: [:new , :create]

  def index
    @users = User.all.reverse
  end


  def get_all_drivers
    @vehicles = Vehicle.all
  #  @shipments = Shipment.includes(:vehicle_type,:shipment_vehicles).where(shipment_vehicles: {status: ShipmentVehicle::ONGOING_VEHICLES })
    render json: { coordinates:  get_driver_bulk_coordinates(@vehicles) }, status: :ok
  end
  
  def show
  end

  def new
    @admin_cargo  = User.new
  end

  def create
    country_id = params[:user][:country_id]
    initial_mobile_number = params[:user][:mobile]
    params[:user][:mobile] = make_phone_number country_id , params[:user][:mobile]
    params[:user][:password] ="12345678"
    @password = params[:user][:password]
    @admin_cargo = User.new(admin_cargo_params)
    @admin_cargo.role = :cargo_owner
    @admin_cargo.mobile_verified = "verified"
    @admin_cargo.verification_code = ""
    @admin_cargo.terms_accepted = TRUE 
    if   @admin_cargo.save
    @admin_cargo.register_as_individual 
      #@admin_cargo.update(mobile_verified: "verified", verification_code: "",terms_accepted: TRUE)
      get_individual_information
      # UserMailer.send_admin_credentials_to_super_admin(current_user.email, @admin_user.id , @password).deliver
    
    else 
      flash[:error] = @admin_cargo.errors.full_messages
       render :new
      end
    

  end
  def get_individual_information

    @current_cargo = User.find_by_mobile(@admin_cargo.mobile)
   

    if( @current_cargo.company.company_type == "individual")
      if  @current_cargo.company.individual_information.present?
        @edit = true
        @info =  @current_cargo.company.individual_information
      else
        @info =  @current_cargo.company.build_individual_information
      end
    else
      redirect_to root_path , notice: "Invalid Request"
    end
    render :get_individual_information

  end
  
  def add_cargo_individual_information
    set_attachment_params
   @current_cargo = User.find params[:individual_information][:userid]
   country_id = @current_cargo.country_id


    company = @current_cargo.company
    if company.individual_information.present?
      
      company.individual_information.update(individual_params)
      flash[:notice] = "Your Profile information is updated Successfully."  
      info = company.individual_information
    else
     

      info = company.build_individual_information(individual_params)
    end
    @current_user.company.update!(tax_registration_no: params[:company][:tax_registration_no]) if current_user.cargo_owner? and params[:company][:tax_registration_no].present?
    info.save
    redirect_to admin_cargo_owners_path , notice: "Cargo created successfully!"
  end

  def set_user
    @user = User.find(params[:id])
  end
  def individual_params
    params.require(:individual_information).permit(:name ,:address ,:secondary_mobile_no, :landline_no, :national_id, :expiry_date,:news_update,:avatar,documents: [])
  end

  private

  def set_users_link
    @users_link= "active"
  end

  def admin_cargo_params
    params.require(:user).permit(:first_name, :last_name , :email, :mobile, :country_id ,:password)
  end

  def set_attachment_params
    if params[:company_information].present?
      begin
        params[:company_information][:avatar] = eval(params[:company_information][:avatar]).first if params[:company_information][:avatar].present?
      rescue SyntaxError => e
        puts "\n\n\n\t\t #{e.message} \n\n"
      end
      begin
          params[:company_information][:documents] = eval(params[:company_information][:documents].first) if params[:company_information][:documents].present?
      rescue SyntaxError => e
        params[:company_information][:documents] = params[:company_information][:documents].first.split(" ") rescue ""
        puts "\n\n\n\t\t #{e.message} \n\n"
      end
      params[:company_information][:documents] = params[:company_information][:documents].blank? ? [] : params[:company_information][:documents]
    elsif params[:individual_information].present?
      begin
        params[:individual_information][:avatar] = eval(params[:individual_information][:avatar]).first if params[:individual_information][:avatar].present?
      rescue SyntaxError => e
        puts "\n\n\n\t\t #{e.message} \n\n"
      end
      begin
        params[:individual_information][:documents] = eval(params[:individual_information][:documents].first) if params[:individual_information][:documents].present?
      rescue SyntaxError => e
        params[:individual_information][:documents] = params[:individual_information][:documents].first.split(" ") rescue ""
        puts "\n\n\n\t\t #{e.message} \n\n"
      end
      params[:individual_information][:documents] = params[:individual_information][:documents].blank? ? [] : params[:individual_information][:documents]
    end
  end


end

app/views/admin/cargo_individual/_attachments.html.erb
<div class = "form-group has-feedback attachment">
  <%= f.hidden_field :documents, multiple: true, class: "js-signed-upload-value"  %>
  <input type="file" class="js-signed-upload" multiple data-presign-url="<%=  presign_upload_companies_path %>" />
    <div class = "attached_files container">
    <p class="js-signed-upload-status">
      <% if f.object.documents.present? %>
        <ul class = "documents_list">
          <%f.object.documents.each do |doc|%>
              <li>
                <a target="_blank" href="<%= doc %>">
                  <span class="remove_thumbnail">x</span>
                  <img src="<%= doc %>" alt="document" class = "document_thumbnail">
                </a>
              </li>
          <%end%>
        </ul>
    <% end %>
    </p>
  </div>
</div>
<script>
  $(".remove_thumbnail").click(function (e) {
      e.preventDefault()
      value = $(this).parents(".form-group").find(".js-signed-upload-value").val()
      value = value.split(" ")
      remove_url = $(this).parents("a").attr("href")
      index = value.indexOf(remove_url)
      value.splice(index, 1)
      $(this).parents(".form-group").find(".js-signed-upload-value").val(value.join(" "))
      $(this).parents("a").addClass("hide")
  })
</script>

app/views/admin/cargo_individual/_avatar.html.erb
<div class = "avatar12">
  <% if @info and @info.avatar.present? %>
      <div class= "">
        <%= image_tag(@info.avatar,class: "avatar" )%>
      </div>
  <%end%>
  <div class="field form-group attachment">
    <%= f.label :avatar , "Your Profile Picture"%><br>
    <%= f.hidden_field :avatar, class: "js-signed-upload-value" %>
    <input type="file" class="js-signed-upload" data-presign-url="<%=  presign_upload_companies_path %>" />
    <p class="js-signed-upload-status">

    </p>
  </div>
</div>

app/views/admin/cargo_individual/_form.html.erb
  <%= render 'layouts/error_messages', object: @admin_user %>
                <%=f.hidden_field :role %>
                

                <div class="form-group">
                  <%= f.label "*" , class: "label_required"%>
                  <%= f.label :first_name%>
                  <%= f.text_field :first_name, autofocus: true,required: true, autocomplete: "First name",class: "form-control", placeholder: "*First name" %>
                </div>

                <div class="form-group">
                  <%= f.label :last_name%>
                  <%= f.text_field :last_name, autofocus: true, autocomplete: "*Last name",class: "form-control", placeholder: "*Last name" %>
                </div>

                <div class="form-group clearfix">
                  <%= f.label "*" , class: "label_required"%>
                  <%= f.label :country_id, "Country"%>
                  <div class="selectCity">
                    <%= f.collection_select(:country_id, Country.all, :id, :display_name,{:prompt => "*Country"}, { class: "form-control",required: true} )%>
                  </div>
                </div>

                <div class="form-group">
                  <%= f.label "*" , class: "label_required"%>
                  <%= f.label :mobile%>
                  <%= f.text_field :mobile , type: :tel,class: "form-control" ,placeholder:  "*Phone number #1" , required: true%>
                </div>

                <div class="form-group">
                  <%= f.label :email%>
                  <%= f.email_field :email, autofocus: true, autocomplete: "email",class: "form-control" ,placeholder:  "Email" %>
                </div>

              
                <div class="form-group">
                  <input type="submit" name="" value="Sign Up" class="btn btn-primary btn-block btn-flat">
                </div>

app/views/admin/cargo_individual/add_vehicle.html.erb
<div class="content-wrapper" style="min-height: 539px;">
  <section class = "content">
    <div class = "container-fluid">
      <div class = "row">
        <div class = "col-md-2"></div>
        <div class = "card-body col-md-7">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Add Vehicle</h3>
              <h2></h2>
            </div>
            <div class="card-body register-card-body">
     <%= form_for @vehicle, :url  => { :action => "add_fleet_individual_vehicle" } do |f| %>
  
                              <%=f.hidden_field :userid ,value: @current_fleet.id %>
           <div class="card-body">
              <div class="form-group">
                <%# f.text_field :mobile , class: "form-control", placeholder: "Driver's Mobile Number"%>
              </div>
              <div class="form-group">
                <%= f.label "*" , class: "label_required"%>
                <%= f.label :registration_number , "Vehicle Registration Number"%>
                <%= f.text_field :registration_number , class: "form-control", placeholder: "*Vehicle Registration No." , required: true%>
              </div>
              <div class="form-group has-feedback">
                <%= f.label "*" , class: "label_required"%>
                <%= f.label :expiry_date, "Expiry Date" %>
                <%= f.text_field :expiry_date , class: "datepicker form-control" ,placeholder:  "*Expiry Date" , required: true %>
              </div>
              <div class="form-group has-feedback">
                <%= f.label "*" , class: "label_required"%>
                <%= f.label :insurance_number, "Insurance Number" %>
                <%= f.text_field :insurance_number , class: " form-control" ,placeholder:  "*Insurance Number", required: true%>
              </div>

              <div class="form-group has-feedback">
                <%= f.label "*" , class: "label_required"%>
                <%= f.label :insurance_expiry_date, "Insurance Expiry Date" %>
                <%= f.text_field :insurance_expiry_date  , class: "datepicker form-control" ,placeholder:  "*Insurance Expiry Date" , required: true %>
              </div>
              <div class="form-group has-feedback">
                <label>Attach Images of Registration/Insurance</label>
                <div class = "form-group has-feedback attachment">
                  <%= f.hidden_field :documents, multiple: true, class: "js-signed-upload-value"  %>
                  <input type="file" class="js-signed-upload" multiple data-presign-url="<%=  presign_upload_companies_path %>" />
                  <div class = "attached_files container">
                    <p class="js-signed-upload-status">
                      <% if @vehicle.documents.present? %>
                        <ul class = "documents_list">
                          <%@vehicle.documents.each do |doc|%>
                            <li>
                              <a target="_blank" href="<%= doc %>">
                                <span class="remove_thumbnail">x</span>
                                <img src="<%= doc %>" alt="document" class = "document_thumbnail">
                              </a>
                            </li>
                          <%end%>
                        </ul>
                      <br><br><br><br>
                    <% end %>
                    </p>
                  </div>
                </div>
              </div>
              <div class="form-group has-feedback">
                <%= f.label :authorization_letter , "Authorization Letter" %>
                <%= f.text_field :authorization_letter, class: "datepicker form-control" ,placeholder:  "Vehicle Authorization Letter/ Noc/ Tafweed" %>
              </div>
              <div class="form-group has-feedback">
                <%= f.check_box :available%>
                <%= f.label :available %>

              </div>

              <div class="form-group has-feedback not_available">
                <div class="row">
                  <div class="col-sm-6">
                    <%= f.label "*" , class: "label_required"%>
                    <%= f.label :not_available_from %>
                    <%= f.text_field :not_available_from , class: "datepicker form-control" ,placeholder:  "*Not Available From" , required: true %>
                    
                  </div>
                  <div class="col-sm-6">
                    <%= f.label "*" , class: "label_required"%>
                    <%= f.label :not_available_to %>
                    <%= f.text_field :not_available_to , class: "datepicker form-control" ,placeholder:  "*Not Available to" , required: true %>
                  </div>
                </div>
              </div>
              
              <div class="form-group">
                <%= f.label "*" , class: "label_required"%>
                <%= f.label :vehicle_type_id, 'vehicle types' %>
                <%= f.collection_select :vehicle_type_id, VehicleType.all.order(code: :desc), :id, :name,{include_blank: "*Vehicle Type"},{class: "form-control" , required: true} %>
              </div>
            </div>
              <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block btn-flat"><%= "ADD" %></button>
                </div>

      <%end%>
    </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/admin/cargo_individual/edit.html.erb
<div class="content-wrapper" style="min-height: 539px;">
  <section class = "content">
    <div class = "container-fluid">
      <div class = "row">
        <div class = "col-md-2"></div>
        <div class = "card-body col-md-7">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Edit GPS</h3>
              <h2></h2>
            </div>
            <div class="card-body register-card-body">
              <%= form_for @moderator_gps, url: admin_gps_vehicle_path do |f|%>
                  <%= render partial: "form", locals: {f: f, action: "Update"}%>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/admin/cargo_individual/get_individual_information.html.erb
<div class="content-wrapper" style="min-height: 539px;">
  <section class = "content">
    <div class = "container-fluid">
      <div class = "row">
        <div class = "col-md-2"></div>
        <div class = "card-body col-md-7">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Add Cargo Individual</h3>
              <h2></h2>
            </div>
            <div class="card-body register-card-body">
     <%= form_for @info, :url  => { :action => "add_cargo_individual_information" } do |f| %>
       <%= render partial: "avatar", locals: {f: f,  info: @info} %>
  
                              <%=f.hidden_field :userid ,value: @current_cargo.id %>
           <div class="form-row">
            <%= f.label "Secondary Mobile No", "Secondary Mobile No."%>
      
            <%= f.text_field :secondary_mobile_no, autofocus: true, autocomplete: "secondary_mobile_no",class: "input-field", placeholder: "Secondary Mobile No" %>
          </div>
    <br>
          <div class="form-row">
            <%= f.label "Landline No.", "Landline No."%>
                     

            <%= f.text_field :landline_no, autofocus: true, autocomplete: "landline_no",class: "input-field" ,placeholder:  "Landline No." %>
          </div> <br>
          <div class="form-row">
            <label> National ID.</label>
                   
            <%= f.text_field :national_id, autocomplete: "national_id", class: "input-field" ,placeholder:  "*National ID  " %>
          </div>   <br>
          <div class="form-row">
            <%= f.label "Expiry Date", "Expiry Date"%>
                   
            <%= f.text_field :expiry_date , autocomplete: "datepicker expiry_date", class: "datepicker input-field" ,placeholder:  "*Expiry Date" %>            
          </div>
             <br>
                <label>Upload All Documents together</label>
           
          <%= render partial: "/companies/attachments", locals: {f: f,  info: @info} %>
          <div class="col-12 sign_up_terms">
              <div class="checkbox icheck">
                <label>
                  <%=f.check_box :news_update , {checked: (@info.new_record? or @info.news_update?)}%>Please send me product updates, news, tips, events, industry insights etc. regularly.
                </label>
              </div>
            </div>

      <div class="col-4">
        <button type="submit" class="btn btn-primary btn-block btn-flat"><%= @edit == true ? "UPDATE" : "SAVE" %></button>
      </div>
    </div>

  <% end %>











    </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/admin/cargo_individual/new.html.erb
<div class="content-wrapper" style="min-height: 539px;">
  <section class = "content">
    <div class = "container-fluid">
      <div class = "row">
        <div class = "col-md-2"></div>
        <div class = "card-body col-md-7">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Add Cargo Individual</h3>
              <h2></h2>
            </div>
            <div class="card-body register-card-body">
              <%= form_for @admin_cargo, url:admin_cargo_individual_index_path do |f|%>
                  <%= render partial: "form", locals: {f: f, action: "Create"}%>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>